name: Render README

# Controls when the workflow will run
on:
  # Schedule updates (every 30 minutes)
  schedule: [{cron: "*/5 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master"]}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  render-readme:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: workflow/nix-shell-action@608eb20401e12c82b204e8e2c6a8b0eebfb5407c
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          packages: curl, jq, bash, coreutils
          script: |
            ./update.sh
            # Skip if no changes.
            [[ ! "$(git status --porcelain)" ]] && echo "No changes." && exit 0
            # Push code.
            git config --global user.name  "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto-updated README"
            git push
