name: Render README

on:
  # Schedule updates (every 30 minutes)
  schedule: [{cron: "*/30 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}

jobs:
  render-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Run update
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          script: |
            ./update.sh
            # Skip if no changes.
            [[ ! "$(git status --porcelain)" ]] && echo "No changes." && exit 0
            # Push code.
            git config --global user.name  "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto-updated README"
            git push
