name: Update README

on:
  # Schedule updates (every 30 minutes)
  schedule: [{cron: "*/30 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}

jobs:
  render-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: workflow/nix-shell-action@v3
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          packages: curl, jq, bash, coreutils
          script: |
            ./update.sh

            # Skip if no changes.
            [[ ! "$(git status --porcelain)" ]] && echo "No changes." && exit 0

            # Push code.
            git config --global user.name  "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "auto update README"
            git push
